apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  namespace: siren
  labels:
    app: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: 879772956301.dkr.ecr.ap-northeast-2.amazonaws.com/user01-order:2
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 400m
              memory: 1000Mi
            requests:
              cpu: 100m
              memory: 1000Mi
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            # initialDelaySeconds: 30
            # timeoutSeconds: 2
            # periodSeconds: 5
            # failureThreshold: 10           
            initialDelaySeconds: 120
            timeoutSeconds: 10
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 180
            timeoutSeconds: 10
            periodSeconds: 5
            failureThreshold: 10
  strategy:
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 50%